# Non-Graded Challenge 4

In [20]:
import numpy as np

In [21]:
t = np.array([[[[23, 50], [7, 12]], [[57, 67], [99, 43]]],
[[[75, 21], [57, 12]], [[87, 26], [18, 84]]]
])
t

array([[[[23, 50],
         [ 7, 12]],

        [[57, 67],
         [99, 43]]],


       [[[75, 21],
         [57, 12]],

        [[87, 26],
         [18, 84]]]])

In [22]:
t.shape

(2, 2, 2, 2)

In [23]:
A = np.array([[23, 50, 19],
[7, 12, 109],
[57, 67, 98]])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [24]:
A.shape

(3, 3)

In [25]:
B = np.array([[17], [22], [19]])
B

array([[17],
       [22],
       [19]])

In [26]:
B.shape

(3, 1)

In [27]:
A @ B

array([[1852],
       [2454],
       [4305]])

In [28]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [29]:
np.linalg.det(A)

131344.0000000002

In [30]:
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])