In [1]:
import numpy as np

In [2]:
vector = np.array([1, 2, 3])
vector

array([1, 2, 3])

In [4]:
matrix = np.array([[1, 2],
                [3, 4],
                [5, 6]])
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
matrix.shape

(3, 2)

### akses elemen matrix

In [9]:
A = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
A[1]

array([4, 5, 6])

In [13]:
A[1, 2]

6

In [14]:
A[1][2]

6

In [16]:
A[:, -1]

array([3, 6, 9])

In [17]:
np.diag(A)

array([1, 5, 9])

In [18]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
B = np.array([[1, 8, 2],
[2, 1, 1],
[4, 0, 1]])
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

penjumlahan, pengurangan, dan pembagian

In [21]:
# matrix dengan matrix
A + B

array([[ 2, 10,  5],
       [ 6,  6,  7],
       [11,  8, 10]])

In [22]:
A - B

array([[ 0, -6,  1],
       [ 2,  4,  5],
       [ 3,  8,  8]])

In [25]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
B

array([[1, 8, 2],
       [2, 1, 1],
       [4, 0, 1]])

In [24]:
B / A

array([[1.        , 4.        , 0.66666667],
       [0.5       , 0.2       , 0.16666667],
       [0.57142857, 0.        , 0.11111111]])

perkalian
- matrix-scalar
- hadarmard product
- matrix-matrix (@)

In [27]:
# matrix-scalar
10 * A

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [28]:
# hadarmard product
A * B

array([[ 1, 16,  6],
       [ 8,  5,  6],
       [28,  0,  9]])

In [29]:
# matrix-matrix multiplication (@)
A @ B

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [30]:
np.dot(A, B)

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [31]:
A.dot(B)

array([[17, 10,  7],
       [38, 37, 19],
       [59, 64, 31]])

In [32]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

inverse

In [36]:
C = np.array([[1, 2],
[3, 4]])
C_adjacent = np.array([[4, -2],
[-3, 1]])

In [38]:
inv_C = 1/np.linalg.det(C) * C_adjacent
inv_C

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [39]:
np.linalg.inv(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [40]:
np.linalg.inv(B)

array([[ 0.11111111, -0.88888889,  0.66666667],
       [ 0.22222222, -0.77777778,  0.33333333],
       [-0.44444444,  3.55555556, -1.66666667]])

In [41]:
np.linalg.det(A)

-9.51619735392994e-16

Tensor

In [45]:
X = np.array([[2, 4, 1, 1],
[0, 9, 4, 2]])
Y = np.array([[6, 4, 5, 0],
[3, 0, 4, 4]])
Z = np.array([[6, 5, 3, 5],
[0, 3, 1, 1]])

In [46]:
list_of_matrix = [X, Y, Z]
tensor = np.array(list_of_matrix)
tensor

array([[[2, 4, 1, 1],
        [0, 9, 4, 2]],

       [[6, 4, 5, 0],
        [3, 0, 4, 4]],

       [[6, 5, 3, 5],
        [0, 3, 1, 1]]])

In [47]:
tensor.shape

(3, 2, 4)

In [48]:
from numpy.linalg import inv, det

In [49]:
det(B)

8.999999999999998

In [50]:
inv(B)

array([[ 0.11111111, -0.88888889,  0.66666667],
       [ 0.22222222, -0.77777778,  0.33333333],
       [-0.44444444,  3.55555556, -1.66666667]])

In [51]:
from numpy.linalg import eig

In [52]:
G = np.array ([[1, 2], [2, 4]])

In [55]:
eigval, eigvec = eig(G)

In [56]:
eigval

array([0., 5.])

In [57]:
eigvec

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [58]:
from numpy import diag

In [59]:
B = eigvec @ diag(eigval) @ inv(eigvec)
B

array([[1., 2.],
       [2., 4.]])