In [1]:
!pip install pandas

In [2]:
import pandas as pd
import numpy as np

In [5]:
pd.Series(['a', 'b', 4])

0    a
1    b
2    4
dtype: object

In [6]:
revenues = pd.Series([5555, 7000, 1980])

In [7]:
revenues

0    5555
1    7000
2    1980
dtype: int64

In [8]:
revenues.values

array([5555, 7000, 1980])

In [9]:
revenues.index

RangeIndex(start=0, stop=3, step=1)

In [11]:
city_revenues = pd.Series(
    [4200, 8000, 6500],
    index = ['Amsterdam', 'Toronto', 'Tokyo']
)
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [13]:
city_employee_count = pd.Series({'Amsterdam': 5, 'Tokyo': 8})
city_employee_count

Amsterdam    5
Tokyo        8
dtype: int64

In [15]:
city_employee_count.keys()

Index(['Amsterdam', 'Tokyo'], dtype='object')

In [20]:
'Tokyo' in city_employee_count

True

In [21]:
5 in city_employee_count

False

In [24]:
city_employee_count.values

array([5, 8])

In [25]:
8 in city_employee_count.values

True

In [27]:
city_data = pd.DataFrame({
    "revenue": city_revenues,
    'employee_count': city_employee_count,
})

In [29]:
city_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Amsterdam to Toronto
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   revenue         3 non-null      int64  
 1   employee_count  2 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 72.0+ bytes


In [30]:
city_data.index

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [31]:
city_data.values

array([[4.2e+03, 5.0e+00],
       [6.5e+03, 8.0e+00],
       [8.0e+03,     nan]])

In [32]:
city_data.columns

Index(['revenue', 'employee_count'], dtype='object')

In [33]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [34]:
city_data.axes

[Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object'),
 Index(['revenue', 'employee_count'], dtype='object')]

In [35]:
city_data.axes[0]

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [36]:
city_data.axes[1]

Index(['revenue', 'employee_count'], dtype='object')

In [37]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [38]:
city_data.keys()

Index(['revenue', 'employee_count'], dtype='object')

In [39]:
'Amsterdam' in city_data

False

In [40]:
'revenue' in city_data

True

In [41]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [42]:
city_revenues['Toronto']

8000

In [43]:
city_revenues[1]

8000

In [45]:
colors = pd.Series(
    ['red', 'purple', 'blue', 'green', 'yellow'],
    index = [1, 2, 3, 5, 8]
)

In [46]:
colors

1       red
2    purple
3      blue
5     green
8    yellow
dtype: object

In [47]:
colors.loc[1]

'red'

In [48]:
colors.iloc[1]

'purple'

In [49]:
colors.iloc[1:3]

2    purple
3      blue
dtype: object

In [52]:
colors.iloc[[0,3]]

1      red
5    green
dtype: object

In [53]:
colors

1       red
2    purple
3      blue
5     green
8    yellow
dtype: object

In [54]:
colors.loc[1:5]

1       red
2    purple
3      blue
5     green
dtype: object

In [57]:
colors.loc[[1,8]]

1       red
8    yellow
dtype: object

In [58]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [59]:
city_revenues.loc['Toronto':]

Toronto    8000
Tokyo      6500
dtype: int64

In [61]:
further_city_data = pd.DataFrame(
    {'revenue': [7000, 3400], 'employee_count': [2, 2]},
    index=['New York', 'Barcelona']
)
further_city_data

revenue  employee_count
New York      7000               2
Barcelona     3400               2

In [62]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [64]:
all_city_data = pd.concat([city_data, further_city_data], sort=False)
all_city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN
New York      7000             2.0
Barcelona     3400             2.0

In [65]:
city_countries = pd.DataFrame(
    {'country': ['Holland', 'Japan', 'Holland', 'Canada', 'Spain'],
    'capital': [1, 1, 0, 0, 0]},
    index = ['Amsterdam', 'Tokyo', "Rotterdam", 'Toronto', 'Barcelona']
)
city_countries

country  capital
Amsterdam  Holland        1
Tokyo        Japan        1
Rotterdam  Holland        0
Toronto     Canada        0
Barcelona    Spain        0

In [66]:
cities = pd.concat([all_city_data, city_countries], axis=1, sort=False)
cities

revenue  employee_count  country  capital
Amsterdam   4200.0             5.0  Holland      1.0
Tokyo       6500.0             8.0    Japan      1.0
Toronto     8000.0             NaN   Canada      0.0
New York    7000.0             2.0      NaN      NaN
Barcelona   3400.0             2.0    Spain      0.0
Rotterdam      NaN             NaN  Holland      0.0

In [69]:
pd.concat([all_city_data, city_countries], axis=1, join='inner')

revenue  employee_count  country  capital
Amsterdam     4200             5.0  Holland        1
Tokyo         6500             8.0    Japan        1
Toronto       8000             NaN   Canada        0
Barcelona     3400             2.0    Spain        0

In [71]:
countries = pd.DataFrame({
    'population_millions': [17, 127, 37],
    'continent': ['Europe', 'Asia', 'North America']},
    index = ['Holland', 'Japan', 'Canada']
)

In [72]:
countries

population_millions      continent
Holland                   17         Europe
Japan                    127           Asia
Canada                    37  North America

In [73]:
cities

revenue  employee_count  country  capital
Amsterdam   4200.0             5.0  Holland      1.0
Tokyo       6500.0             8.0    Japan      1.0
Toronto     8000.0             NaN   Canada      0.0
New York    7000.0             2.0      NaN      NaN
Barcelona   3400.0             2.0    Spain      0.0
Rotterdam      NaN             NaN  Holland      0.0

In [74]:
pd.merge(cities, countries, left_on='country', right_index=True)

revenue  employee_count  country  capital  population_millions  \
Amsterdam   4200.0             5.0  Holland      1.0                   17   
Rotterdam      NaN             NaN  Holland      0.0                   17   
Tokyo       6500.0             8.0    Japan      1.0                  127   
Toronto     8000.0             NaN   Canada      0.0                   37   

               continent  
Amsterdam         Europe  
Rotterdam         Europe  
Tokyo               Asia  
Toronto    North America

In [75]:
pd.merge(cities, countries, left_on='country', right_index=True, how='left')

revenue  employee_count  country  capital  population_millions  \
Amsterdam   4200.0             5.0  Holland      1.0                 17.0   
Tokyo       6500.0             8.0    Japan      1.0                127.0   
Toronto     8000.0             NaN   Canada      0.0                 37.0   
New York    7000.0             2.0      NaN      NaN                  NaN   
Barcelona   3400.0             2.0    Spain      0.0                  NaN   
Rotterdam      NaN             NaN  Holland      0.0                 17.0   

               continent  
Amsterdam         Europe  
Tokyo               Asia  
Toronto    North America  
New York             NaN  
Barcelona            NaN  
Rotterdam         Europe