In [1]:
from pkg import mod1

print(mod1.kitchen)\

set


In [2]:
!pip install numpy

In [3]:
!pip install pandas

In [4]:
import numpy as np

In [5]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [7]:
tinggi = np.array([1.7, 1.8, 2.0])
berat = np.array([62.9, 78.5, 86.7])

berat / tinggi

array([37.        , 43.61111111, 43.35      ])

In [27]:
print(np.arange(4, 10, 2))

[4 6 8]


In [14]:
arr = np.array([1, 2, 3, 4])
arr = np.append(arr, [1, 2, 3])

In [15]:
np.delete(arr, 3)

array([1, 2, 3, 1, 2, 3])

In [16]:
np.sort(arr)

array([1, 1, 2, 2, 3, 3, 4])

In [19]:
b = np.sort(arr)
b = b[::-1]
b

array([4, 3, 3, 2, 2, 1, 1])

In [20]:
b.ndim

1

In [21]:
b.shape

(7,)

In [24]:
a  = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
matriks = a.reshape(2, 3)
print(matriks)

[[0 1 2]
 [3 4 5]]


In [29]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.expand_dims(a, axis=1)
print(b.shape)
c = np.expand_dims(a, axis=0)
print(c.shape)

(6, 1)
(1, 6)


In [31]:
arr = np.array([2, 3, 7, 8, 9])
print(arr[2:6])

[7 8 9]


In [32]:
print(arr[2:5:3])

[7]


In [37]:
print(arr[::-1])

[list([1, 3, 6, 8]) list([2, 3, 7, 8, 9])]


In [39]:
arr = np.array([[2, 3, 7, 8, 9],
                [1, 3, 6, 8, 4]])

In [40]:
print(arr[1, 1:3])

[3 6]


In [42]:
print(arr[0:4, 1])

[3 3]


In [45]:
arr = np.array([[2, 3, 7, 8, 9],
                [1, 3, 6, 8, 7],
                [1, 3, 6, 8, 7]])
print(arr[1:3, 2:4])

[[6 8]
 [6 8]]


In [ ]:
a = np.array([[1, 2, 3, 4],
                5, 6, 7, 8],
                9, 10, 11, 12])

In [48]:
a_1 = ([[1, 1],
        [2, 2]])
a_2 = ([[3, 3],
        [4, 4]])
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [49]:
data_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [55]:
new_arr = data_1.reshape(2, -1, 3)
new_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
def convert(fahr, kelv):
    cels = fahr * 1.8 +32
    cels2 = kelv - 273.15
    return cels, cels2
print("temperature in celcius (C) =", convert(32, 20))

temperature in celcius (C) = (89.6, -253.14999999999998)


In [57]:
def convert(fahr):
    cels = fahr * 1.8 + 32.0
    return cels
print(convert(32))

89.6


In [68]:
def temp_converter(ftemp):
    ctemp = (ftemp - 32) * (5/9)
    ktemp = ctemp + 273.15
    return [ftemp, ctemp, ktemp]
print(temp_converter(72))

[72, 22.22222222222222, 295.3722222222222]


In [69]:
def sum(numbers):
    total = 0
    for x in numbers:
        total += x
    return total
print(sum((8, 2, 3, 0, 7)))

20


In [78]:
def myfunc():
    st = 'jojon'
    y = 35
    return st, y
print(myfunc()[1])

35
